export const PRODUCT_FETCH_START = "PRODUCT_FETCH_START";
export const PRODUCT_FETCH_SUCCESS = "PRODUCT_FETCH_SUCCESS";
export const PRODUCT_FETCH_FAIL = "PRODUCT_FETCH_FAIL";

export const CATEGORY_FETCH_START = "CATEGORY_FETCH_START";
export const CATEGORY_FETCH_SUCCESS = "CATEGORY_FETCH_SUCCESS";
export const CATEGORY_FETCH_FAIL = "CATEGORY_FETCH_FAIL";

export const CHART_FETCH_START = "CHART_FETCH_START";
export const CHART_FETCH_SUCCESS = "CHART_FETCH_SUCCESS";
export const CHART_FETCH_FAIL = "CHART_FETCH_FAIL";

export const CATEGORY_FILTER_UPDATE = "CATEGORY_FILTER_UPDATE"

export const BRANDS_FETCH_START = "BRANDS_FETCH_START"
export const BRANDS_FETCH_SUCCESS = "BRANDS_FETCH_SUCCESS"
export const BRANDS_FETCH_FAIL = "BRANDS_FETCH_FAIL"